version: '3'

services:
  acme-sh:
    build: ./build
    container_name: acme-sh
    restart: always
    env_file: .env
    volumes:
      - ./acme-logs:/var/log/acme-logs
      - ./acme.sh:/acme.sh
      - ./build/crontab:/crontab
